apiVersion: v1
kind: Namespace
metadata:
  name: academy-workshop
  namespace: academy-workshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-workshop
  namespace: academy-workshop
  labels:
    app: academy-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-workshop
  template:
    metadata:
      labels:
        app: academy-workshop
    spec:
      serviceAccountName: academy-workshop
      containers:
        - name: academy-workshop
          image: codydearkland/academy-workshop:latest
          imagePullPolicy: Always
          env:
          - name: AWS_DEFAULT_REGION
            value: "us-east-2"
          - name: ENABLE_IRP
            value: "true"
          ports:
            - name: web
              containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: academy-workshop
  name: workshop-lb
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:us-west-1:955116512041:certificate/98950c1e-e516-4c39-b70a-093f4e4b3128
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: https
      port: 443
      targetPort: 5000
  selector:
    app: academy-workshop
  type: LoadBalancer
